# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details
# for poetry see https://docs.readthedocs.io/en/stable/build-customization.html#install-dependencies-with-poetry

version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.12"
  jobs:
    post_install:
      - pip install poetry
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH poetry install --with docs

sphinx:
  configuration: docs/conf.py
