name: Benchmark

on:
  push:
    branches-ignore:
      - "*"
    tags:
      - "*"
  pull_request:
    types:
      - closed
      - ready_for_review
      - review_requested
  workflow_dispatch:

jobs:
  benchmark:
    name: Benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python 🐍
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: "poetry"
      - run: poetry install --with benchmark
      - name: Generate objects
        run: |
          cd benchmarks/
          poetry run python run.py 0 -eko -geko
          poetry run python run.py 1 -eko -geko
      - name: Compile GRV
        run: |
          cd benchmarks/
          poetry run python -m numpy.f2py -c -m grvphoton grvphoton.f
      - name: Run comparison
        run: |
          cd benchmarks/
          echo "### LO ###"
          poetry run python compare.py 0 --df-grv -pid u,g,S -nep 0
          poetry run python compare.py 0 --df-grv -pid u,g,S -nep 2
          echo "### NLO ###"
          poetry run python compare.py 1 --df-qcdnum -pid u,g,S -nep 0
          poetry run python compare.py 1 --df-qcdnum -pid u,g,S -nep 2
